services:
  mysql:
    image: mysql
    volumes:
      - ./.data:/var/lib/mysql
      - ./config:/usr/config
      - ./queries:/usr/queries
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

